#!/usr/bin/lua

local read_size = 64
local cal_2g_offset = 0x1000
local cal_5g_offset = 0x5000
local cal_5g_2_offset = 0x9000
local cal_data_size = 0x2f20
local mtd_art = io.popen("cat /proc/mtd | grep 'art' | grep -o 'mtd.'")
local file = nil
local cal_2g = 0
local cal_5g = 0
local cal_5g_2 = 0

if mtd_art then
        file = io.open("/dev/" .. string.gsub(mtd_art:read("*all"),"\n",""), "r")
        mtd_art:close()
end

if file == nil then
        print("nil file")
else
        file:seek("set", cal_2g_offset)
        local bytes_read_2g = file:read(read_size)
        for byte in string.gfind(bytes_read_2g, ".") do
                if string.byte(byte) ~= 0xff then
                        cal_2g = 1
                        break
                end
        end
		
        local uci = require "luci.model.uci"
        local uci_p= uci.cursor("/etc/profile.d")
        local rf_band = uci_p:get_profile("DEVINFO", "RFBand")
        local tri_band = uci_p:get_profile("tri_band", "support")
        if "yes" == tri_band then
                file:seek("set", cal_5g_2_offset + cal_data_size - read_size)
                local bytes_read_5g_2 = file:read(read_size)
                for byte in string.gfind(bytes_read_5g_2, ".") do
                        if string.byte(byte) ~= 0xff then
                                cal_5g_2 = 1
                                break
                        end
                end

                if cal_2g == 1 and cal_5g_2 == 1 then
                        print("true")
                else
                        print("false")
                end
                return
        else 
                if "Dual" == rf_band then
                        file:seek("set", cal_5g_offset + cal_data_size - read_size)
                        local bytes_read_5g = file:read(read_size)

                        for byte in string.gfind(bytes_read_5g, ".") do
                                if string.byte(byte) ~= 0xff then
                                        cal_5g = 1
                                        break
                                end
                        end
                        
                        if cal_2g == 1 and cal_5g == 1 then
                                print("true")
                        else
                                print("false")
                        end
                        return
                end
        end

        if cal_2g == 1 then
                print("true")
        else
                print("false")
        end
	return
end
