#!/bin/sh /etc/rc.common
# Copyright (c) 2016 Shenzhen TP-LINK Technologies Co.Ltd.
# Author		Wang Hao<wanghao@tp-link.com.cn>

SERVICE_DAEMONIZE=1

START=99
STOP=99

start() {
    if [[ "$(uci get bluetooth.settings.mode)" == "normal" ]]; then
        /usr/sbin/handheld_radar -s
    fi
	return 0
}
