#!/bin/sh /etc/rc.common

START=21
STOP=21

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/leds -l i
    procd_set_param respawn 3600 5 5

    procd_close_instance

    return 0
}

stop_service() {
    return 0
}

reload_service() {
    stop
    start
}