#!/bin/sh /etc/rc.common
# Copyright (C) 2017 Tp-link.com
# Author: Xu Shengfu <xushengfu@tp-link.com.cn>
# Date: 27Nov17

START=40
# Stop before leds

USE_PROCD=1

. /lib/functions.sh

start_service() {
    
    config_load conn_indicator
    config_get_bool enabled conn_indicator 'enabled' '1'
    [ "${enabled}" -gt 0 ] || {
        #plc is up ?
        ifconfig eth2 > /dev/null
        if [[ "$?" = "0" ]]; then
            ubus call leds power '{"state":"on"}'
            ubus call leds conn '{"state":"online"}'
        else
            ubus call leds switch "{\"state\":\"off\"}" &
        fi

    }
    config_clear

}
