#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Tp-link.com
# Author: xsfour <xushengfu@tp-link.com.cn>
# Date: 17Mar18

# boot before repacd
START=43

. /lib/functions.sh

local init_failed=0

__init_wireless() {
    local vif="$1"
#    local old="$2"
#    local new="$3"
    local type

    type=$(uci_get wireless "$vif")
    [ -n "$type" ] || {
        ${init_failed}=$((init_failed+1))
        return 1
    }

    uci_set wireless "$vif" wps_pbc 1
    return 0
}

boot() {
    local changed=0

    local prefix=$(uci_get wps wps uuid_prefix)
    [ -n "$prefix" ] || {
        local uuid=$(uuidgen)
        uuid=${uuid:0:23}
        uci_add wps setting wps
        uci_set wps wps uuid_prefix "$uuid"
        uci_commit wireless
        changed=1
    }

    local migration_wireless=$(uci_get wireless migration wps 0)
    local migration=$(uci_get wps migration self 0)

    [ $migration -gt ${migration_wireless} ] && {
        config_load wps
        config_foreach __init_wireless wifi-iface ${migration_wireless} $migration
        config_clear

        [ ${init_failed} -gt 0 ] || {
            uci_add wireless migration migration
            uci_set wireless migration wps "$migration"
            uci_commit wireless
            changed=1
        }
    }

    [ "$changed" -gt 0 ] && {
        save_config
    }
}
